### PR TITLE
Index view for Computer ready for testing

### LINKED ISSUE #16: Computers View All
## Acceptance Criteria for #11 

**Given** a user wants to view all computers
**When** the user clicks on the Computers item in the navigation bar
**Then** the user should see a list of all computers
**And** each item should be a hyperlink that can be clicked to view the details

### PR DESCRIPTION
**Pull request by ewlusky**
# Description
 This implements the List view for the Computer table.  It also adds a section in the documentation on how to access the computer table.
 Fixes #16 
 ## Type of change
 Please delete options that are not relevant.
- [x] New feature (non-breaking change which adds functionality)
 # Testing Instructions
 Start SQL Server Management Studio

Run BangazonDatabaseCreateSeed.sql in SSMS

Update the appsetting.json in Visual Studio community to reflect your desktop and your server

In the terminal, git fetch --all and git checkout el-computer-idx to switch branches

Start the program by cd'ing into the WorkforceManagement (make sure you are deep enough, the .sln file is a few WorkforceManagement directories deep) and using the command dotnet run.

Once the program is running, navigate to your browser and go to the localhost address shown in the command prompt that opens up when you run the program. Click on the Computers link in the navbar, and you should see a list with all Computers in the database.  There should be three, and each should have a details and delete button, neither of which should currently work.
 # Checklist:
 - [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by Rian501** [comment]
Ticket #16 says that, rather than a details button, the name itself should be a link that leads to the detail view. Heads up.
Build runs successfully.

**Comment by ewlusky** [comment]
Fixed issue with details button not being the item itself.

**Comment by Rian501** [comment]
Looks good.
When clicking on the link, it tries to take me to something with the ID of 0, so I think something is off with your IDs in terms of leading to the correct path.

**Comment by ewlusky** [comment]
Emily was right I forgot to pull the ComputerId in the sql query.  Fixed now.

**Pull request merged**
